version: '3.8'

services:
  iot_gateway:
    build:
      context: ./IoT_Gateway
    container_name: iot_gateway
    depends_on:
      - mqtt
    ports:
      - "50051:50051"
      - "5000:5000"
      - "8000:8000"
    networks:
      - iot_net

  sensor_grpc:
    build:
      context: ./Sensores/SensorGRPC
    container_name: sensor_grpc
    depends_on:
      - iot_gateway
    networks:
      - iot_net
  
  sensor_ws:
    build:
      context: ./Sensores/SensorWS
    container_name: sensor_ws
    depends_on:
      - iot_gateway
    networks:
      - iot_net

  sensor_rest:
    build:
      context: ./Sensores/SensorRest
    container_name: sensor_rest
    depends_on:
      - iot_gateway
    networks:
      - iot_net

  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt
    ports:
      - "1883:1883"
    networks:
      - iot_net
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iot_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - iot_net

  subscriber:
    build: 
      context: ./MQTT_Subscriber
    container_name: subscriber
    depends_on:
      - mqtt
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=iotdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - iot_net


networks:
  iot_net:
    driver: bridge
